import {
  AreaGWAdultOnewayTicketRequest,
  AreaGWAdultRoundTripTicketRequest,
  AreaGWFXAdultOnewayTicketRequest,
  AreaGWFXAdultRoundTripTicketRequest,
  AreaGWFXHalfOnewayTicketRequest,
  AreaGWFXHalfRoundTripTicketRequest,
  AreaGWHalfOnewayTicketRequest,
  EnjuRWAdultOnewayTicketRequest,
  EnjuRWFXAdultOnewayTicketRequest,
  EnjuRWFXAdultRoundTripTicketRequest,
  EnjuRWFXChildOnewayTicketRequest,
  EnjuRWFXChildRoundTripTicketRequest,
  EnjuRWFXHalfOnewayTicketRequest,
  EnjuRWFXHalfRoundTripTicketRequest
} from "@/db/model";

export interface Database {
  areagw_adult_oneway_ticket_req: AreaGWAdultOnewayTicketRequest
  areagw_adult_roundtrip_ticket_req: AreaGWAdultRoundTripTicketRequest
  areagw_half_oneway_ticket_req: AreaGWHalfOnewayTicketRequest
  areagw_fx_adult_oneway_ticket_req: AreaGWFXAdultOnewayTicketRequest
  areagw_fx_adult_roundtrip_ticket_req: AreaGWFXAdultRoundTripTicketRequest
  areagw_fx_half_oneway_ticket_req: AreaGWFXHalfOnewayTicketRequest
  areagw_fx_half_roundtrip_ticket_req: AreaGWFXHalfRoundTripTicketRequest
  enjurw_adult_oneway_ticket_req: EnjuRWAdultOnewayTicketRequest
  enjurw_fx_adult_oneway_ticket_req: EnjuRWFXAdultOnewayTicketRequest
  enjurw_fx_adult_roundtrip_ticket_req: EnjuRWFXAdultRoundTripTicketRequest
  enjurw_fx_half_oneway_ticket_req: EnjuRWFXHalfOnewayTicketRequest
  enjurw_fx_half_roundtrip_ticket_req: EnjuRWFXHalfRoundTripTicketRequest
  enjurw_fx_child_oneway_ticket_req: EnjuRWFXChildOnewayTicketRequest
  enjurw_fx_child_roundtrip_ticket_req: EnjuRWFXChildRoundTripTicketRequest
}
